server:
  port: 8080

spring:
  application:
    name: search-service
debug: false

alibaba:
  elasticsearch:
    hostlist: 127.0.0.1:9200 #多个节点中间用逗号分隔;192.168.21.131:9200,192.168.21.132:9200,192.168.21.133:9200
  course:
    source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time